spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
#    url: jdbc:mysql://localhost:3306/profiles?tinyInt1isBit=false
 #   username: root
  #  password:
  jpa:
    hibernate:
      ddl-auto: update


  resources:
    static-locations[0]: file:src/main/resources/static/
    static-locations[1]: classpath:/static/

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: "coderefugees@gmail.com"
    password: "@123321@"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
